# Generated by Django 3.1.3 on 2020-12-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='bio',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
